import React from 'react';
// Fix: Import Stack component from @mui/material
import { Box, Card, CardContent, List, ListItemButton, ListItemText, Skeleton, Stack, Typography } from '@mui/material';
import { Lightbulb as LightbulbIcon } from '@mui/icons-material';

interface PromptSuggestionsProps {
    suggestions: string[];
    onSelectSuggestion: (suggestion: string) => void;
    isLoading: boolean;
}

/**
 * A component that displays alternative prompt suggestions generated by the AI.
 * It shows a loading state while fetching and allows users to click a suggestion to use it.
 * @param {PromptSuggestionsProps} props The component props.
 * @returns {React.ReactElement | null} The rendered suggestions panel or null if not loading and no suggestions exist.
 */
export const PromptSuggestions: React.FC<PromptSuggestionsProps> = ({ suggestions, onSelectSuggestion, isLoading }) => {
    // Render a loading state with skeletons for a better user experience.
    if (isLoading) {
        return (
            <Card>
                <CardContent>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2 }}>
                        <LightbulbIcon color="primary" sx={{ animation: "pulse 1.5s infinite" }} />
                        <Typography variant="h5" component="h2">Generating Ideas...</Typography>
                    </Box>
                    <Stack spacing={1}>
                        <Skeleton variant="rounded" height={40} />
                        <Skeleton variant="rounded" height={40} />
                        <Skeleton variant="rounded" height={40} />
                    </Stack>
                </CardContent>
            </Card>
        );
    }
    
    // Do not render the component if there are no suggestions to display.
    if (suggestions.length === 0) {
        return null;
    }

    return (
        <Card>
            <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
                    <LightbulbIcon color="primary" />
                    <Typography variant="h5" component="h2">Need Inspiration?</Typography>
                </Box>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                    Here are a few alternative ideas. Click one to use it as your prompt.
                </Typography>
                <List disablePadding>
                    {suggestions.map((suggestion, index) => (
                        <ListItemButton
                            key={index}
                            onClick={() => onSelectSuggestion(suggestion)}
                            sx={{ borderRadius: 1, mb: 0.5 }}
                        >
                            <ListItemText primary={suggestion} />
                        </ListItemButton>
                    ))}
                </List>
            </CardContent>
        </Card>
    );
};